### PR TITLE
Added an effect by voice

### LINKED ISSUE #39: Per voice FX ?
Is it possible to have individual FX for each voice? Or to play a single note with an effect?

### PR DESCRIPTION
**Pull request by giann**
Resolves #39

To change effect for a voice: `<voice number><effect name><value>`
If the effect is different than the current one, it's replaced (current
one is disconnected and replaced by the new effect)

### CODE REVIEW

**Comment by giann** [comment]
If all those additional effects have a performance impact: we can only initialize them when activated by the user.

**Comment by giann** [comment]
@neauoire did you get a chance to look at it?

**Comment by neauoire** [comment]
It's quite an involved PR, I have pulled it but not tested it too much yet, give me a few more days. I'm leaving for Amsterdam tonight and I'll be back in a week, I'll merge it then :)

**Comment by baitcode** [comment]
Did it ever get to master?

**Comment by neauoire** [comment]
I haven't because I'm waiting for one of the school program using Pilot to end(in June), I assured the teacher that I wouldn't change it "too much" until then.

**Comment by cyclopssound** [comment]
Hey there, sorry to bump, started using Orca with Pilot and started thinking about fx per channel and wondered if anyone was working on it. Would love to see this merged to master!

**Comment by Kyle-Shanks** [comment]
@cyclopssound 
I made a knock-off version of pilot that addresses per channel effects and presets and things if you're interested
https://github.com/Kyle-Shanks/Aeronaut

**Pull request closed without merging**
