### PR TITLE
Stop recording with esc key

### PR DESCRIPTION
**Pull request by mactkg**
Implemented #15.

### CODE REVIEW

**Comment by neauoire** [comment]
Perfect thanks :)

**Comment by mactkg** [comment]
@neauoire Oh thank you for fast response! 🏎

but I want to find a more suitable place of this code.
https://github.com/mactkg/Pilot/blob/ba0a8193cff1b8f3ae8aabc97cc2ed53c4ce2c35/desktop/sources/index.html#L54-L61

My first idea is write the code into `commander.js` because `orca`'s code handle `onkeydown` or `onkeyup` in `commander.js`. However, Pilot's `comander.js` has different role a bit, and it's weird to write there.
If you have any good idea, please refactor the code 🙏

**Comment by neauoire** [comment]
You could also replace with:

```
controller.add("default","File","Stop Recording",() => { pilot.recorder.stop() },"Escape")
```

**Comment by mactkg** [comment]
Ah, indeed 🙄
I'll fix it later~

**Comment by neauoire** [comment]
Fixed :)

**Pull request merged**
