### PR TITLE
Preparing Workshop

### PR DESCRIPTION
**Pull request by neauoire**

### CODE REVIEW

**Comment by ryanramage** [comment]
Wow. cool. I will have to check this out. Sorry I've been distracted, but glad you are able to move forward on this. Looks pretty minimal which is great for new users.

**Comment by neauoire** [comment]
It's going to be awesome : ) I was thinking of using it for the workshop in the UK, I want to have something pretty stable for next month!

**Comment by ryanramage** [comment]
A couple thoughts, based on playing with it

 I know you have 16 channels of mono synths, but you can make each channel poly synths by using https://tonejs.github.io/docs/r13/PolySynth and then passing in the synth type (AM, FM, etc). That way it behaves more like traditional midi

I guess if you did the above you'd have to change back to having the channel in the route to change the ADSR and the effects, so maybe it's a design you've made to make it simpler.

All the channels run through the same effects, and I am not sure if that is by design. You could do a layout like the following:

```
0 00f7 ....A.D.     1 00f7 ....C...
CHO f9 |||||||| .   CHO f9 ||||||||
TRE 0? ..........     TRE 0? ..........
BIT  0? ..........     BIT  0? ..........
CHE 0f ..........    CHE 0f ..........
DIS f9 |||||||||| .   DIS f9 ||||||||||
DEL 07 | .            DEL 07 |
REV f7 |||||||| .    REV f7 ||||||||
FEE 07 | .            FEE 07 |
```
eg 16 times. But it does make it more intimidating. Also notice I added two notes on channel 0.

Anyway, just suggestions

**Comment by ryanramage** [comment]
And if there is any chance of recording your workshop, that'd be great.

**Comment by neauoire** [comment]
I was just trying to keep it simple for the new users.
I was wondering, do you have any idea how I could record the audio output from tone?

**Comment by ryanramage** [comment]
ok fair enough. Simple is good. 

Here is really good code for recording. 
https://github.com/mmckegg/wave-recorder/blob/master/index.js

Tone just uses web audio nodes , so just plug the destination one into this.

 I know you are not a fan of many dependencies, so you could copy it (and the related https://github.com/mmckegg/audio-buffer-stream)

**Comment by ryanramage** [comment]
maybe this is just simpler
https://www.youtube.com/watch?v=VHCv3waFkRo

**Comment by neauoire** [comment]
Do you think you could give me a hand with this?
https://codepen.io/jakealbaugh/pen/QVqgBE/

I can't say I've often used these sorts of things like blobs and things.

**Comment by ryanramage** [comment]
I see you got it working. nice!

**Pull request merged**
